[package]
authors = ["Chaoqian Xu <chaoranxu@gmail.com>"]
edition = "2021"
name = "maxwell-utils"
version = "0.6.0"

[dependencies]
dycovec = "0.1.1"
num_cpus = "1.13.1"
once_cell = "1.10.0"
actix = "0.13.0"
