[package]
authors = ["Chaoqian Xu <chaoranxu@gmail.com>"]
edition = "2021"
name = "maxwell-utils"
version = "0.10.0"

[dependencies]
log = "0.4.20"

futures = "0.3.28"
futures-intrusive = "0.5.0"
futures-util = "0.3.28"
tokio = {version = "1.32.0", features = ["full"]}

actix = "0.13.1"
actix-codec = "0.5.1"
actix-web = "4.4.0"
actix-web-actors = "4.2.0"
awc = "3.2.0"

ahash = "0.8.3"
bytes = "1.4.0"
dashmap = "5.5.3"
dycovec = "0.1.1"
num_cpus = "1.16.0"
once_cell = "1.18.0"

maxwell-protocol = {git = "https://github.com/maxwell-dev/maxwell-protocol-rust.git", tag = "v0.15.0"}

[dev-dependencies]
log4rs = "1.2.0"
