[package]
authors = ["Chaoqian Xu <chaoranxu@gmail.com>"]
edition = "2021"
name = "maxwell-utils"
version = "0.10.19"

[dependencies]
log = "0.4.20"

futures = "0.3.29"
futures-intrusive = "0.5.0"
tokio = {version = "1.34.0", features = ["full"]}

actix = "0.13.1"
fastwebsockets = {version = "0.5.0", features = ["upgrade", "unstable-split"]}
hyper = {version = "0.14.26", features = ["http1", "client", "tcp"]}

ahash = "0.8.6"
anyhow = "1.0.75"
bytes = "1.5.0"
dashmap = "5.5.3"
dycovec = "0.1.1"
num_cpus = "1.16.0"
once_cell = "1.19.0"

maxwell-protocol = {git = "https://github.com/maxwell-dev/maxwell-protocol-rust.git", tag = "v0.21.0"}

[dev-dependencies]
futures-util = "0.3.29"
log4rs = "1.2.0"
